package entities;
// Generated May 12, 2018 7:44:03 PM by Hibernate Tools 4.3.1



/**
 * Ingredient generated by hbm2java
 */
public class Ingredient  implements java.io.Serializable {


     private IngredientId id;

    public Ingredient() {
    }

    public Ingredient(IngredientId id) {
       this.id = id;
    }
   
    public IngredientId getId() {
        return this.id;
    }
    
    public void setId(IngredientId id) {
        this.id = id;
    }




}


